MODEL:
  class_path: 'src.model.unet.UNet'
  weight_path: './weights/unet_weights_07072025.pt'
  KWARGS:
    num_in_channels: 3
    num_out_channels: 4
    dims: [32, 64, 128, 256, 320, 320, 320, 320]
    depth: 2

TRAIN:
  COMPILE: false
  CUDNN_BENCHMARK: false
  OPTIMIZER:
    class_path: 'torch.optim.AdamW'
    KWARGS:
      lr: 0.00005
      weight_decay: 0.01
  CRITERION:
    class_path: 'src.loss.loss.DiceFocalLoss'
    KWARGS:
      alpha: 2.0
  KWARGS:
    epochs: 20
    metrics: []
    device: 'cpu'

HYPERPARAMETER_SEARCH:
  SEARCH_SPACE: false

DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 1
    shuffle: true
    num_workers: 0
    pin_memory: false
    drop_last: false

DATASET:
  class_path: 'src.dataset.ecg_scan.ECGScanDataset'
  KWARGS: {}
  TRAIN:
    KWARGS:
      data_path: '../../data/westmead_ptbxl/train'
    TRANSFORM:
      class_path: 'src.transform.vision.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.vision.RandomCrop'
            KWARGS: {size: [512, 512]}
          - class_path: 'src.transform.vision.GreyscaleTransform'
            KWARGS: {}
          - class_path: 'src.transform.vision.RandomJPEGCompressionTransform'
            KWARGS: {quality: [35, 98], p: 0.4}
          - class_path: 'src.transform.vision.RandomGradientOverlay'
            KWARGS: {p: 0.5, opacity_range: [-0.15, 0.15]}
          - class_path: 'src.transform.vision.RefineMask'
            KWARGS: {}
  VAL:
    KWARGS:
      data_path: '../../data/westmead_ptbxl/val'
    TRANSFORM:
      class_path: 'src.transform.vision.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.vision.RandomCrop'
            KWARGS: {size: [512, 512]}
          - class_path: 'src.transform.vision.GreyscaleTransform'
            KWARGS: {}
          - class_path: 'src.transform.vision.RefineMask'
            KWARGS: {}
  TEST:
    KWARGS:
      data_path: '../../data/westmead_ptbxl/test'
